<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Filesystem\Filesystem;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends EntityRepository
{    
    public function getAllOrderedByPosition() {
        $q = "select c from AppBundle:Blog c order by c.position asc";
        return $this->getEntityManager()->createQuery($q)->getResult();
    }
    
    public function getByPosition($position) {
        $q = "select b from AppBundle:Blog b where b.position = :position";
        return $this->getEntityManager()->createQuery($q)->setParameter('position', $position)->getOneOrNullResult();
    }
    
    public function getBySlug($slug) {
        $dql = 'select b from AppBundle:Blog b where b.slug = :slug';
        return $this->getEntityManager()->createQuery($dql)->setParameter(':slug', $slug)->getOneOrNullResult();
    }
    
    public function countAll() {
        return $this->createQueryBuilder('c')
            ->select('count(c.id)')
            ->getQuery()
            ->getSingleScalarResult();
    }
    
    public function getAll($sortColumn, $sortDirection, $pageSize, $page) {
        $sql = "SELECT c FROM AppBundle:Blog c";
        $query = $this->getEntityManager()->createQuery($sql);
        
        if (!empty($sortColumn)) {
            if (!empty($sortDirection)) {
                $query->orderBy($sortColumn, $sortDirection);
            }
            else {
                $query->orderBy($sortColumn);
            }
        }
        
        if ($pageSize != null && $pageSize != ""){
            $query->setMaxResults($pageSize);
        }
        if ($page != null && $page != "" && $page != 1){            
            $query->setFirstResult(($page - 1) * $pageSize);
        }
        
        return $query->getResult();
    }
    
    public function removeImage($blog, $image_storage_dir) {
        $oldImage = $blog->getImage();
        if ($oldImage != null) {
            /*$fullPath = sprintf("%s%s\\%s",
                $image_storage_dir,
                $oldImage->getPath(),
                $oldImage->getName());*/
            $fullPath = 
                $image_storage_dir .
                    DIRECTORY_SEPARATOR .
                    $oldImage->getPath() .
                    DIRECTORY_SEPARATOR .
                    $oldImage->getUuid() . '.' . $oldImage->getExtension();
            
            $fs = new Filesystem();
            $fs->remove($fullPath);

            $em = $this->getEntityManager();

            $blog->setImage(null); 
            $em->remove($oldImage);
            $em->flush();
        }
        
        return $blog;
    }
    
    public function isSlugUnique($slug, $blogId = null) {
        $dql = 'select count(b.id) from AppBundle:Blog b where b.slug = :slug';
        if ($blogId != null) {
            $dql = $dql . ' and b.id != :blogId';
        }
        $q = $this->getEntityManager()->createQuery($dql);
        $q->setParameter(':slug', $slug);
        if ($blogId != null) {
            $q->setParameter(':blogId', $blogId);
        }
        return $q->getSingleScalarResult() == 0;
    }
}
