<?php

namespace AppBundle\Entity;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    private $categories = null; // categories dictionary for fast check
    
    public function getCategoryBySlug($slug) {
        // initialise $categories
        if ($this->categories == null) {
            $result = $this
                ->getEntityManager()
                ->createQuery('select c from AppBundle:Category c')
                ->getResult();            
            
            $this->categories = array();
            foreach ($result as $c) {
                $this->categories[$c->getSlug()] = $c;
            }
        }
        
        // actual get/check
        if (array_key_exists($slug, $this->categories)) {
            return $this->categories[$slug];
        } else {
            return null;
        }
    }
    
    
    public function getAllOrderedByPosition() {
        return $this
                ->getEntityManager()
                ->createQuery('select c from AppBundle:Category c order by c.position asc')
                ->getResult();
    }
}
