<?php

namespace AppBundle\Entity;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{    
    public function getAllOrderedByPosition() {
        $q = "select c from AppBundle:Category c order by c.position asc";
        return $this->getEntityManager()->createQuery($q)->getResult();
    }
}
