<?php

namespace AppBundle\Entity;

/**
 * EquipmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipmentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll($subcategory) {
        $sql = "select e from AppBundle:Equipment e where e.subcategoryID = {$subcategory->getID()}";
        return $this
                ->getEntityManager()
                ->createQuery($sql)
                ->getResult();
    }
}
