<?php

namespace AppBundle\Entity;

/**
 * EquipmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipmentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllBySubcategory($subcategoryId) {
        $sql = "select e from AppBundle:Equipment e where e.subcategory = :subcategoryId";
        $query = $this->getEntityManager()->createQuery($sql);
        $query->setParameter('subcategoryId', $subcategoryId);
        return $query->getResult();        
    }    
    public function clearFeatures($equipmentId) {
        $sql = 'delete from AppBundle:EquipmentFeature ef where ef.equipment = :equipment';
        $q = $this->getEntityManager()->createQuery($sql);
        $q->setParameter(':equipment', $equipmentId);
        $q->execute();
    }
    public function saveFeatures($equipmentId, $features) {
        $this->clearFeatures($equipmentId);
        $em = $this->getEntityManager();
        foreach ($features as $id => $text) {
            $ef = new EquipmentFeature();
            $ef->setEquipment($em->getReference('AppBundle:Equipment', $equipmentId));
            $ef->setFeature($em->getReference('AppBundle:Feature', $id));
            $ef->setName($text);
            $em->persist($ef);
        }
        $em->flush();
        $em->clear();
    }
}
