<?php

namespace AppBundle\Entity;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteById($id) {
        $sql = "delete from AppBundle:Image i where i.id = :id";
        $query = $this->getEntityManager()->createQuery($sql);
        $query->setParameter('id', $id);
        return $query->getResult();        
    }
}
