<?php

namespace AppBundle\Entity;

/**
 * SubcategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubcategoryRepository extends \Doctrine\ORM\EntityRepository
{
    private $subcategories = null; // categories dictionary for fast check
    
    public function getSubcategoryBySlug($slug) {
        // initialise $subcategories
        if ($this->subcategories == null) {
            $result = $this
                ->getEntityManager()
                ->createQuery('select c from AppBundle:Subcategory c')
                ->getResult();            
            
            $this->subcategories = array();
            foreach ($result as $s) {
                $this->subcategories[$s->getSlug()] = $s;
            }
        }
        // actual get/check
        if (array_key_exists($slug, $this->subcategories)) {
            return $this->subcategories[$slug];
        } else {
            return null;
        }
    }
    

    public function getAllOrderedByPosition() {
        $q = "select s from AppBundle:Subcategory s join s.category c order by c.position asc, s.position asc";
        return $this->getEntityManager()->createQuery($q)->getResult();
    }
}
