<?php

namespace AppBundle\Entity;

/**
 * SubcategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubcategoryRepository extends \Doctrine\ORM\EntityRepository
{
    private $subcategories = null; // subcategories dictionary for fast check
    
    public function getSubcategoryBySlug($slug) {
        // initialise $categories
        if ($this->subcategories == null) {
            $result = $this
                ->getEntityManager()
                ->createQuery('select c from AppBundle:Subcategory c')
                ->getResult();            
            
            $this->subcategories = array();
            foreach ($result as $c) {
                $this->subcategories[$c->getSlug()] = $c;
            }
        }
        
        // actual get/check
        if (array_key_exists($slug, $this->subcategories)) {
            return $this->subcategories[$slug];
        } else {
            return null;
        }
    }
    
    
    public function getAllOrderedByPosition($category = null) {
        if ($category == null)
            $sql = 'select s from AppBundle:Subcategory s order by s.categoryID asc, s.position asc';
        else
            $sql = "select s from AppBundle:Subcategory s where s.categoryID = {$category->getID()} order by s.position asc";
        return $this
                ->getEntityManager()
                ->createQuery($sql)
                ->getResult();
    }
}
